In [1]:
#Untitled6
# Linear Algebra
import numpy as np

# Data Processing
import pandas as pd

# Data visualization
import matplotlib.pyplot as plt
import time
%matplotlib inline
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
# Algorithm 

from sklearn.svm import SVC, LinearSVC

In [2]:
import io
start_time = time.time()
kidney_data = pd.read_csv('NewRBFdataset.csv')
kidney_data.head()

,1,48,80,1.02,1.1,0,1.2,1.3,0.1,0.2,...,15.4,44,7800,5.2,1.4,1.5,0.3,1.6,0.4,0.5
0,0,7,50,1.020,4,0,1,1,0,0,...,11.3,38,6000,3.9,0,0,0,1,0,0
1,2,62,80,1.010,2,3,1,1,0,0,...,9.6,31,7500,3.9,0,1,0,0,0,1
2,3,48,70,1.005,4,0,1,0,1,0,...,11.2,32,6700,3.9,1,0,0,0,1,1
3,2,51,80,1.010,2,0,1,1,0,0,...,11.6,35,7300,4.6,0,0,0,1,0,0
4,1,60,90,1.015,3,0,1,1,0,0,...,12.2,39,7800,4.4,1,1,0,1,1,0

In [3]:
#kidney_data = kidney_data.sample(frac = 1)
kidney_data=kidney_data.to_numpy()

In [4]:
x_train = kidney_data[:,1:]
x_test = kidney_data[375:,1:]
y_train = kidney_data[:,0]
y_test = kidney_data[375:,0]

In [5]:
def pnn_classifier(example) :
    summation = [None] * 5
    class_observations = 0
    for classi in range(5) :
        summation[classi] = 0.0
        class_observations=0
        for observation in range(0,385) :
            product = 0.0
            if y_train[observation] == classi :
                class_observations += 1
                for feature in range(0,24) :
                    if feature == 0:
                        product += pow(((example[feature])-x_train[observation][feature]),3)
                    elif feature == 11:
                        product += pow(((example[feature])-x_train[observation][feature]),4)
                    else :
                        product += pow((example[feature]-x_train[observation][feature]),2)
                        
                try:
                    summation[classi] += math.exp(-(math.sqrt(product)/(2.0*pow(0.0292,2))))
                except:
                    pass
        
        summation[classi]=(summation[classi]/class_observations)
                
    return winner_takes_all(summation)

In [6]:

def main() :
    
    time.sleep(1)
    t3=time.time()
    count = 0
    for i in range(0,24) :
        a = pnn_classifier(x_test[i])
        if a == y_test[i] :
            count += 1
    accuracy = count/24
    print("Accuracy:",accuracy)
    
    
    print("--- %s seconds ---" % (time.time() - t3))
    print("--- %s seconds ---" % (time.time() - start_time))

In [7]:
def winner_takes_all(summation) :
    maxval = summation[0]
    best = 0
    for classi in range(5) :
        if summation[classi] > maxval :
            best = classi
            maxval = summation[classi]
    return best

In [8]:
main()

Accuracy: 0.9166666666666666
--- 0.26169419288635254 seconds ---
--- 3.647199869155884 seconds ---